/* auto-generated by tools/gen_data.py - do not edit */
#ifndef WF_DATA_H
#define WF_DATA_H

#include <stdint.h>

#define NUM_JOINTS 23
typedef struct { const int16_t *frames; uint16_t nframes; } wf_motion_t;
enum { MOT_IDLE, MOT_JAB, MOT_KICK, MOT_GUARD, MOT_HIT, MOT_KO, MOT_COUNT };
extern wf_motion_t wf_motions[MOT_COUNT];
#define WF_BASE_YAW_Q16 137972
enum {
    JI_Hips = 0,
    JI_Spine = 1,
    JI_Spine1 = 2,
    JI_Spine2 = 3,
    JI_Neck = 4,
    JI_Head = 5,
    JI_HeadTop_End = 6,
    JI_LeftShoulder = 7,
    JI_LeftArm = 8,
    JI_LeftForeArm = 9,
    JI_LeftHand = 10,
    JI_RightShoulder = 11,
    JI_RightArm = 12,
    JI_RightForeArm = 13,
    JI_RightHand = 14,
    JI_LeftUpLeg = 15,
    JI_LeftLeg = 16,
    JI_LeftFoot = 17,
    JI_LeftToeBase = 18,
    JI_RightUpLeg = 19,
    JI_RightLeg = 20,
    JI_RightFoot = 21,
    JI_RightToeBase = 22,
};
#endif /* WF_DATA_H */
