/*
 * WIREFIGHT 32X - fixed point helpers (Q16.16)
 *
 * The SH2 has no FPU, so all game math is integer based.
 */
#ifndef WF_FIXED_H
#define WF_FIXED_H

#include <stdint.h>
#include "32x.h"

typedef int32_t fixed;

#define FIX_ONE        ((fixed)0x00010000)
#define FIX_HALF       ((fixed)0x00008000)
#define FIX_PI         ((fixed)205887)       /* 3.14159265 * 65536 */
#define FIX_TWO_PI     ((fixed)411775)       /* 6.28318530 * 65536 */

/* compile-time float -> fixed (for constant tables only) */
#define FIXC(x)        ((fixed)((x) * 65536.0 + ((x) >= 0 ? 0.5 : -0.5)))

static inline fixed imul(fixed a, fixed b)
{
    return (fixed)(((int64_t)a * (int64_t)b) >> 16);
}

/* division via the SH2 DIVU unit: signed 64/32 -> 32 division in ~39
 * cycles, overlaps with regular execution */
static inline fixed fixdiv(fixed a, fixed b)
{
    int64_t n = ((int64_t)a) << 16;
#ifdef WF_HOST
    return (fixed)(n / b);
#else
    fixed q;
    SH2_DIVU_DVSR = b;
    SH2_DIVU_DVDNTH = (int32_t)(n >> 32);
    SH2_DIVU_DVDNTL = (int32_t)(uint32_t)n;
    /* the sh2 takes up to 39 cycles to finish the division; burn some
       time so a read on real hardware can't see a partial quotient
       (picodrive completes the division at the triggering write, but
       this costs almost nothing and keeps hardware correctness) */
    { volatile int spin = 8; while (spin--) ; }
    /* quotient of a 64/32 division lands in dvdntl, not dvdnt */
    q = SH2_DIVU_DVDNTL;
    return q;
#endif
}

static inline int fix2int(fixed v) { return v >> 16; }
static inline fixed int2fix(int v) { return (fixed)(v << 16); }

/* integer square root of a 64-bit value (16 iterations) */
static inline uint32_t isqrt64(uint64_t v)
{
    uint64_t res = 0, bit = 1ull << 62;

    while (bit > v)
        bit >>= 2;
    while (bit != 0) {
        if (v >= res + bit) {
            v -= res + bit;
            res = (res >> 1) + bit;
        } else {
            res >>= 1;
        }
        bit >>= 2;
    }
    return (uint32_t)res;
}

/* sqrt of Q16.16 -> Q16.16 */
static inline fixed fixsqrt(fixed x)
{
    if (x <= 0)
        return 0;
    return (fixed)isqrt64(((uint64_t)(uint32_t)x) << 16);
}

/* -------- sine/cosine table (generated by gen_data.py) -------- */
/* 1024 entries over [0, 2*pi), Q16.16, plus cos table with 256-entry
 * overlap so that cos_p(x) = sincos(x + FIX_PI/2) wraps safely.      */
extern fixed wf_sin_tab[1024 + 256];

/* multiply constant: radians(Q16.16) -> table index << 8 (262144/2pi) */
#define WF_IDXMUL  41722u

static inline fixed fixsin(fixed a)
{
    /* a is Q16.16 radians */
    fixed r = a % FIX_TWO_PI;
    uint32_t idx;
    if (r < 0)
        r += FIX_TWO_PI;
    /* idx = r/(2pi) * 1024 with 8 fractional index bits */
    idx = (uint32_t)(((uint64_t)(uint32_t)r * WF_IDXMUL) >> 16);
    {
        uint32_t i = idx >> 8, f = idx & 0xFF;
        fixed s0 = wf_sin_tab[i], s1 = wf_sin_tab[i + 1];
        return s0 + (fixed)(((int64_t)(s1 - s0) * (int32_t)f) >> 8);
    }
}

static inline fixed fixcos(fixed a)
{
    return fixsin(a + FIX_PI / 2);
}

#endif /* WF_FIXED_H */
