/* auto-generated by tools/gen_data.py - do not edit */
#ifndef WF_FONT_H
#define WF_FONT_H
#include <stdint.h>
/* 5x7 font for ASCII 32..126, one byte per row, bits 4..0 left..right */
extern uint8_t wf_font7[95][7];
#endif
