#!/usr/bin/env python3
"""
WIREFIGHT 32X - asset -> C generator

Reads the original wirefight motions.npz and emits:
  src-sh2/data.h / data.c   motion data (Q4.12 int16), joint indices,
                            precomputed BASE_YAW, motion table
  src-sh2/sintab.c          wf_sin_tab (Q16.16, 1024+256 entries)
  src-sh2/font.c / font.h   5x7 font (normal + big text) 

Usage: gen_data.py <motions.npz> <output_dir>
"""
import math
import sys
from pathlib import Path

import numpy as np

RED = "\033[91m"
RST = "\033[0m"


def q(v, bits):
    x = int(round(v * (1 << bits)))
    lim = 1 << (15)
    assert -lim <= x < lim, f"value {v} out of int16 range at Q{12}"
    return x


def gen_motions(npz_path, outdir):
    d = np.load(npz_path)
    joints = [str(j) for j in d["joints"]]
    names = ["idle", "jab", "kick", "guard", "hit", "ko"]
    ji = {n: i for i, n in enumerate(joints)}

    idle0 = d["idle"][0]
    lr = idle0[ji["LeftShoulder"]] - idle0[ji["RightShoulder"]]
    fwd = np.cross([0.0, 1.0, 0.0], [lr[0], 0.0, lr[2]])
    fwd /= math.sqrt((fwd * fwd).sum())
    base_yaw = math.atan2(fwd[0], fwd[2])

    hdr = []
    src = []
    hdr.append("/* auto-generated by tools/gen_data.py - do not edit */")
    hdr.append("#ifndef WF_DATA_H\n#define WF_DATA_H\n")
    hdr.append("#include <stdint.h>\n")
    hdr.append(f"#define NUM_JOINTS {len(joints)}")
    hdr.append("typedef struct { const int16_t *frames; uint16_t nframes; } wf_motion_t;")
    hdr.append("enum { MOT_IDLE, MOT_JAB, MOT_KICK, MOT_GUARD, MOT_HIT, MOT_KO, MOT_COUNT };")
    hdr.append("extern wf_motion_t wf_motions[MOT_COUNT];")
    hdr.append(f"#define WF_BASE_YAW_Q16 {int(round(base_yaw * 65536))}")
    hdr.append("enum {")
    for i, n in enumerate(joints):
        hdr.append(f"    JI_{n} = {i},")
    hdr.append("};")
    hdr.append("#endif /* WF_DATA_H */")

    src.append("/* auto-generated by tools/gen_data.py - do not edit */")
    src.append('#include "data.h"\n')
    for name in names:
        a = d[name]  # (frames, joints, 3) float32
        nf, nj, _ = a.shape
        src.append(f"static int16_t mot_{name}[{nf} * {nj} * 3] = {{")
        vals = []
        for f in range(nf):
            row = []
            for jn in range(nj):
                for c in range(3):
                    row.append(str(q(float(a[f, jn, c]), 12)))
            vals.append("    " + ",".join(row))
        src.append(",\n".join(vals))
        src.append("};\n")
    src.append("wf_motion_t wf_motions[MOT_COUNT] = {")
    for name in names:
        src.append(f'    {{ mot_{name}, {len(d[name])} }},')
    src.append("};\n")

    (outdir / "data.h").write_text("\n".join(hdr) + "\n")
    (outdir / "data.c").write_text("\n".join(src) + "\n")
    print(f"motions: {', '.join(f'{n}={len(d[n])}f' for n in names)}, base_yaw={base_yaw:.6f}")


def gen_sintab(outdir):
    n = 1024 + 256
    vals = []
    for i in range(n):
        v = int(round(math.sin(i * 2.0 * math.pi / 1024.0) * 65536.0))
        vals.append(str(v))
    lines = ["/* auto-generated by tools/gen_data.py - do not edit */",
             "#include <stdint.h>",
             "int32_t wf_sin_tab[1024 + 256] = {"]
    for i in range(0, n, 8):
        lines.append("    " + ",".join(vals[i:i + 8]) + ",")
    lines.append("};\n")
    (outdir / "sintab.c").write_text("\n".join(lines))
    print(f"sintab: {n} entries")


FONT = {
    "A": ".###.|#...#|#...#|#####|#...#|#...#|#...#",
    "B": "####.|#...#|#...#|####.|#...#|#...#|####.",
    "C": ".###.|#...#|#....|#....|#....|#...#|.###.",
    "D": "###..|#..#.|#...#|#...#|#...#|#..#.|###..",
    "E": "#####|#....|#....|####.|#....|#....|#####",
    "F": "#####|#....|#....|####.|#....|#....|#....",
    "G": ".###.|#...#|#....|#.###|#...#|#...#|.###.",
    "H": "#...#|#...#|#...#|#####|#...#|#...#|#...#",
    "I": ".###.|..#..|..#..|..#..|..#..|..#..|.###.",
    "J": "..###|...#.|...#.|...#.|...#.|#..#.|.##..",
    "K": "#...#|#..#.|#.#..|##...|#.#..|#..#.|#...#",
    "L": "#....|#....|#....|#....|#....|#....|#####",
    "M": "#...#|##.##|#.#.#|#.#.#|#...#|#...#|#...#",
    "N": "#...#|##..#|#.#.#|#..##|#...#|#...#|#...#",
    "O": ".###.|#...#|#...#|#...#|#...#|#...#|.###.",
    "P": "####.|#...#|#...#|####.|#....|#....|#....",
    "Q": ".###.|#...#|#...#|#...#|#.#.#|#..#.|.##.#",
    "R": "####.|#...#|#...#|####.|#.#..|#..#.|#...#",
    "S": ".####|#....|#....|.###.|....#|....#|####.",
    "T": "#####|..#..|..#..|..#..|..#..|..#..|..#..",
    "U": "#...#|#...#|#...#|#...#|#...#|#...#|.###.",
    "V": "#...#|#...#|#...#|#...#|#...#|.#.#.|..#..",
    "W": "#...#|#...#|#...#|#.#.#|#.#.#|##.##|#...#",
    "X": "#...#|#...#|.#.#.|..#..|.#.#.|#...#|#...#",
    "Y": "#...#|#...#|.#.#.|..#..|..#..|..#..|..#..",
    "Z": "#####|....#|...#.|..#..|.#...|#....|#####",
    "0": ".###.|#...#|#..##|#.#.#|##..#|#...#|.###.",
    "1": "..#..|.##..|..#..|..#..|..#..|..#..|.###.",
    "2": ".###.|#...#|....#|..##.|.#...|#....|#####",
    "3": "####.|....#|....#|.###.|....#|....#|####.",
    "4": "...#.|..##.|.#.#.|#..#.|#####|...#.|...#.",
    "5": "#####|#....|#....|####.|....#|....#|####.",
    "6": ".###.|#...#|#....|####.|#...#|#...#|.###.",
    "7": "#####|....#|...#.|..#..|..#..|..#..|..#..",
    "8": ".###.|#...#|#...#|.###.|#...#|#...#|.###.",
    "9": ".###.|#...#|#...#|.####|....#|#...#|.###.",
    " ": ".....|.....|.....|.....|.....|.....|.....",
    "!": "..#..|..#..|..#..|..#..|..#..|.....|..#..",
    ".": ".....|.....|.....|.....|.....|.##..|.##..",
    ",": ".....|.....|.....|.....|.##..|.##..|.#...",
    ":": ".....|.##..|.##..|.....|.##..|.##..|.....",
    "-": ".....|.....|.....|#####|.....|.....|.....",
    "/": "....#|....#|...#.|..#..|.#...|#....|#....",
    "<": "...#.|..#..|.#...|#....|.#...|..#..|...#.",
    ">": ".#...|..#..|...#.|....#|...#.|..#..|.#...",
    "+": ".....|..#..|..#..|#####|..#..|..#..|.....",
    "(": "...#.|..#..|.#...|.#...|.#...|..#..|...#.",
    ")": ".#...|..#..|...#.|...#.|...#.|..#..|.#...",
    "=": ".....|.....|#####|.....|#####|.....|.....",
}


def gen_font(outdir):
    # map ASCII 32..127, unknown glyphs -> '?'
    order = [chr(c) for c in range(32, 127)]

    def glyph_for(ch):
        if ch in FONT:
            return FONT[ch]
        return FONT["W"] if ch.isalpha() else FONT[" "]

    rows = []
    for ch in order:
        g = glyph_for(ch).split("|")
        assert len(g) == 7
        bs = []
        for r in g:
            assert len(r) == 5
            b = 0
            for i, c in enumerate(r):
                if c == "#":
                    b |= 1 << (4 - i)
            bs.append(b)
        rows.append(bs)

    hdr = ["/* auto-generated by tools/gen_data.py - do not edit */",
           "#ifndef WF_FONT_H", "#define WF_FONT_H", "#include <stdint.h>",
           "/* 5x7 font for ASCII 32..126, one byte per row, bits 4..0 left..right */",
           "extern uint8_t wf_font7[95][7];",
           "#endif"]
    src = ["/* auto-generated by tools/gen_data.py - do not edit */",
           '#include "font.h"',
           "uint8_t wf_font7[95][7] = {"]
    for bs in rows:
        src.append("    { " + ",".join(f"0x{b:02x}" for b in bs) + " },")
    src.append("};\n")
    (outdir / "font.h").write_text("\n".join(hdr) + "\n")
    (outdir / "font.c").write_text("\n".join(src))
    print(f"font: {len(rows)} glyphs")


def main():
    npz = Path(sys.argv[1])
    outdir = Path(sys.argv[2])
    outdir.mkdir(parents=True, exist_ok=True)
    gen_motions(npz, outdir)
    gen_sintab(outdir)
    gen_font(outdir)
    print("OK")


if __name__ == "__main__":
    main()
